### PR TITLE
kiev to kyiv

### PR DESCRIPTION
**Pull request by PeerRich**

### CODE REVIEW

**Comment by PeerRich** [comment]
fixes #27

**Comment by MaxSmile** [comment]
Oops, I did see your pull request and the same for Kyiv. But also Odessa -> Odesa

**Comment by iwex** [comment]
@kevinroberts 
check please!

**Comment by kevinroberts** [comment]
added to v 1.2.2

**Comment by iwex** [comment]
Thanks!

**Comment by PeerRich** [comment]
tried updating to 1.2.2 and getting this now: 

CleanShot 2024-07-26 at 14 23 52@2x


see my PR: https://github.com/calcom/cal.com/pull/15927

**Comment by iwex** [comment]
I guess it's because timezone should be "Europe/Kiev"
But city is Kyiv

**Comment by kevinroberts** [comment]
@PeerRich Looks like IANA has 
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#KYIV
https://en.wikipedia.org/wiki/Time_in_Ukraine Europe/Kyiv listed. The validation used for those timezone IDs appears to be outdated?

**Pull request merged**
